version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=pricing_user
      - DB_PASSWORD=pricing_password
      - DB_NAME=pricing_dashboard
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pricing-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=pricing_dashboard
      - MYSQL_USER=pricing_user
      - MYSQL_PASSWORD=pricing_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../../src/lib/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - pricing-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=pricing_user
      - PMA_PASSWORD=pricing_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - pricing-network

volumes:
  mysql_data:

networks:
  pricing-network:
    driver: bridge
